### ISSUE TITLE
Circom Sources

### ISSUE THREAD

**Issue by humayunj** [zkp-ld/rdf-proofs#8]
Do we've circom source files for the compiled circuits. Would be good to get inspiration from and create new circuits

**Comment by yamdan** [comment]
Yes, we do have the source files for the compiled circuits. You can find them in my separate repository here: [rdf-proofs-circom](https://github.com/yamdan/rdf-proofs-circom).

**Comment by humayun-novo** [comment]
> Yes, we do have the source files for the compiled circuits. You can find them in my separate repository here: [rdf-proofs-circom](https://github.com/yamdan/rdf-proofs-circom).

Thank you @yamdan

**Comment by humayunj** [comment]
> Yes, we do have the source files for the compiled circuits. You can find them in my separate repository here: [rdf-proofs-circom](https://github.com/yamdan/rdf-proofs-circom).

Thank you @yamdan
